/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FromIndexRouteImport } from './routes/from.index'
import { Route as FromIataRouteImport } from './routes/from.$iata'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FromIndexRoute = FromIndexRouteImport.update({
  id: '/from/',
  path: '/from/',
  getParentRoute: () => rootRouteImport,
} as any)
const FromIataRoute = FromIataRouteImport.update({
  id: '/from/$iata',
  path: '/from/$iata',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/from/$iata': typeof FromIataRoute
  '/from/': typeof FromIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/from/$iata': typeof FromIataRoute
  '/from': typeof FromIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/from/$iata': typeof FromIataRoute
  '/from/': typeof FromIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/from/$iata' | '/from/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/from/$iata' | '/from'
  id: '__root__' | '/' | '/privacy' | '/from/$iata' | '/from/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  FromIataRoute: typeof FromIataRoute
  FromIndexRoute: typeof FromIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from/': {
      id: '/from/'
      path: '/from'
      fullPath: '/from/'
      preLoaderRoute: typeof FromIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from/$iata': {
      id: '/from/$iata'
      path: '/from/$iata'
      fullPath: '/from/$iata'
      preLoaderRoute: typeof FromIataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  FromIataRoute: FromIataRoute,
  FromIndexRoute: FromIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
