/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutTheDataRouteImport } from './routes/about-the-data'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as FromIndexRouteImport } from './routes/from.index'
import { Route as FromIataRouteImport } from './routes/from.$iata'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheDataRoute = AboutTheDataRouteImport.update({
  id: '/about-the-data',
  path: '/about-the-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FromIndexRoute = FromIndexRouteImport.update({
  id: '/from/',
  path: '/from/',
  getParentRoute: () => rootRouteImport,
} as any)
const FromIataRoute = FromIataRouteImport.update({
  id: '/from/$iata',
  path: '/from/$iata',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-the-data': typeof AboutTheDataRoute
  '/privacy': typeof PrivacyRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/from/$iata': typeof FromIataRoute
  '/countries/': typeof CountriesIndexRoute
  '/from/': typeof FromIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-the-data': typeof AboutTheDataRoute
  '/privacy': typeof PrivacyRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/from/$iata': typeof FromIataRoute
  '/countries': typeof CountriesIndexRoute
  '/from': typeof FromIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-the-data': typeof AboutTheDataRoute
  '/privacy': typeof PrivacyRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/from/$iata': typeof FromIataRoute
  '/countries/': typeof CountriesIndexRoute
  '/from/': typeof FromIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-the-data'
    | '/privacy'
    | '/countries/$slug'
    | '/from/$iata'
    | '/countries/'
    | '/from/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-the-data'
    | '/privacy'
    | '/countries/$slug'
    | '/from/$iata'
    | '/countries'
    | '/from'
  id:
    | '__root__'
    | '/'
    | '/about-the-data'
    | '/privacy'
    | '/countries/$slug'
    | '/from/$iata'
    | '/countries/'
    | '/from/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutTheDataRoute: typeof AboutTheDataRoute
  PrivacyRoute: typeof PrivacyRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  FromIataRoute: typeof FromIataRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  FromIndexRoute: typeof FromIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-data': {
      id: '/about-the-data'
      path: '/about-the-data'
      fullPath: '/about-the-data'
      preLoaderRoute: typeof AboutTheDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from/': {
      id: '/from/'
      path: '/from'
      fullPath: '/from/'
      preLoaderRoute: typeof FromIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from/$iata': {
      id: '/from/$iata'
      path: '/from/$iata'
      fullPath: '/from/$iata'
      preLoaderRoute: typeof FromIataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutTheDataRoute: AboutTheDataRoute,
  PrivacyRoute: PrivacyRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  FromIataRoute: FromIataRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  FromIndexRoute: FromIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
